### ISSUE TITLE
google sheets extension - details

### ISSUE THREAD

**Issue by pacharanero** [rcpch/digital-growth-charts-documentation#13]
@eatyourpeas could you share the links for the Google Sheets extension?
Is it in version control somewhere or in the weird Google Apps Script walled garden?
Can we publish it somehow?
Can we mirror the source in GH?

**Comment by fabform** [comment]
Handy to [find google sheet id](https://fabform.io/a/how-to-find-google-sheet-id)

**Comment by anchit-chandran** [comment]
#77
