### ISSUE TITLE
Down Syndrome guidance 

### ISSUE THREAD

**Issue by magdaumerska** [rcpch/digital-growth-charts-documentation#22]
@pacharanero and @eatyourpeas 

We have this guidance for Down Syndrome charts from Dr Liz Marder, which is of clinical importance to add to the documentation portal. 
Do we need a sub-section under Clinician > Chart information for Health staff > Down Syndrome charts? 

Many thanks,

Magda 
[Instructions for Downs Syndrom charts.pdf](https://github.com/rcpch/digital-growth-charts-documentation/files/6453269/Instructions.for.Downs.Syndrom.charts.pdf)

**Comment by pacharanero** [comment]
I have added the PDF as a downloadable document, to the Chart information for Health staff page, under a Down's Syndrome subsection.

For now this means it's easily findable and in due course we can update it, reformat it, and add as native documentation (ie remove it from the PDF and put it in the docs)
