### ISSUE TITLE
Fix the Dark Mode so that the header bar and RCPCH logo invert on Dark toggle

### ISSUE THREAD

**Issue by pacharanero** [rcpch/digital-growth-charts-documentation#24]
At present, although Dark Mode works for the page content, the header bar doesn't switch.
This is probably because we have hard-coded CSS for some of this in `docs/_stylesheets/extra.css`
![image](https://user-images.githubusercontent.com/2348385/124561074-64c1fd80-de35-11eb-96b7-41f00220bfac.png)

MkDocs info on this is here https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#custom-colors

Ideally we'd want the top header bar to invert to a dark colour, probably a shade lighter than the dark content background?
Text would need to change colour for contrast and readability.
RCPCH logo may need to be re-coloured (maybe switching where used, but keeping the same colours?)

**Comment by ChakshuVerma** [comment]
Hello, I'd like to work on this issue. Should I Proceed?

**Comment by eatyourpeas** [comment]
Thank you @ChakshuVerma. If you are happy to fork the repo, and make a pull request to a new branch?

**Comment by a-wei-william** [comment]
@pacharanero has this issue been resolved? I was thinking of giving this one a shot

**Comment by pacharanero** [comment]
The new combined demo and documentation site loads several external pages in iframes. Those external pages won't be aware of the dark or light mode so I'm dark mode they will look wrong. So actually I think we might be best off closing this issue and just removing the dark/light option. I was also not sure how the RCPCH brand team would view dark mode in terms of colours.

**Comment by pacharanero** [comment]
closing as I think we should just have a light mode at this stage

**Comment by pacharanero** [comment]
This was mentioned today in my call with @joknight25 so I will just @mention the relevant people so they can be aware of why we have decided we just don't need this feature.

Nobody is asking for it - it was only that it was _possible_ using the documentation tooling software we have chosen (see [their own site](https://squidfunk.github.io/mkdocs-material/getting-started/) which has light/dark toggle in the header)

Thanks for your comments @Jo-Ball @kirsten-olson (copied below)
> Dark mode toggle: We can't obviously see this – is it just a device setting? In principle, seems fine to us

Good to know it wouldn't be a problem in principle. I'm going to close this for now, but we can bring it back if we decide to do it. Crucially it is not as simple as fixing the header alone - because the **demo chart** is loaded in an iframe like this `<iframe src="https://rcpch.github.io/digital-growth-charts-react-client/"/>` the iframe portion of the screen would not be aware of the toggle. Se we'd actually need to have 2 versions of the demo, statically hosted, one in 'dark' and one in 'light'.
