### ISSUE TITLE
Review documentation on Gestational Age Correction

### ISSUE THREAD

**Issue by pacharanero** [rcpch/digital-growth-charts-documentation#39]
* Ensure the GAC pages of documentation cover the topic properly
* Add discussion on post-term GAC, for example the 'reversed' correction which applies to 43- or 44-weekers
* Point to the discussion on this subject in the Archives

**Comment by eatyourpeas** [comment]
This was discussed at length at project board today
Final outcome:
1. There is no international precedent on what to do about post 40 week babies. 
2. Age correction should continue at all gestations
3. Any babies born post term should be corrected backwards. Where this happens, the corrected age (rendered as a cross) may appear before the chronological age (a dot).
4. To discuss this in the open press the project board will consider a publication in the academic press to discuss electronic charts in general, with a section on age correction to discuss this issue.

**Comment by pacharanero** [comment]
> Where this happens, the corrected age (rendered as a cross) may appear before the chronological age (a dot).

I thought in the situation of post term babies being corrected for gestation, the cross would be **after** the dot - they would be given a corrected age that is older than their chronological age? Because it's the opposite for pre-term, in my head at least.

Point 4 may be assisted by collecting some high-quality screenshots of examples of GAC being applied in our charts, including a pre-term and post-term example.
