### ISSUE TITLE
Cyber Essential Certificate needs to be updated

### ISSUE THREAD

**Issue by pacharanero** [rcpch/digital-growth-charts-documentation#58]
@magdaumerska please attache the updated one here and I will add it to the site

**Comment by magdaumerska** [comment]
Hi @pacharanero please see the attachment with the new certificate. 
Best,
Magda 
[Cyber Essentials Certificate 2023.pdf](https://github.com/rcpch/digital-growth-charts-documentation/files/10805784/Cyber.Essentials.Certificate.2023.pdf)

**Comment by pacharanero** [comment]
closed with https://github.com/rcpch/digital-growth-charts-documentation/commit/0da1c3010b404fb9d0621679a3bb572890961d52

**Comment by pacharanero** [comment]
@magdaumerska worth noting that this new certificate expires in early 2023 so we will need a new one once we've renewed
