### ISSUE TITLE
need data on Charlotte Weldon - couldn't find any

### ISSUE THREAD

**Issue by pacharanero** [rcpch/digital-growth-charts-documentation#6]
https://github.com/rcpch/digital-growth-charts-documentation/blob/6881d611b104de65e930dad2db12b2e31550bbda/docs/about/team.md#L16-L17

**Comment by magdaumerska** [comment]
Hi @pacharanero Charlotte Weldon is IS Programme Manager at RCPCH. Charlotte joined only the first meeting and whilst the main contributions are made by Andrew Palmer and Joanne Hatton, I would suggest to remove Charlotte from the list.

**Comment by pacharanero** [comment]
OK great will do

**Comment by pacharanero** [comment]
Closed by #18
