### ISSUE TITLE
These images look terrible - need better ones

### ISSUE THREAD

**Issue by pacharanero** [rcpch/digital-growth-charts-documentation#9]
https://github.com/rcpch/digital-growth-charts-documentation/blob/9e0aa8d2808cadf496a53b7f31c6f7a3e2656339/docs/clinician/chart-information-health-staff.md#L31-L32

view the documentation site here <https://rcpch.github.io/digital-growth-charts-documentation/clinician/chart-information-health-staff>

These images are quite small. I think they were originally embedded in some source documents which the Project board asked to add to the main documentation. Could we get hold of some nicer versions of them?

Consider non-pink/blue

I will embed them once we have nicer images

**Comment by magdaumerska** [comment]
Hi @pacharanero, 

Can we please remove those images for now? They aren't owned by RCPCH so we are in the process of creating our own - will share those as soon as they are ready. 

Thank you,
Magda

**Comment by pacharanero** [comment]
OK will do

**Comment by pacharanero** [comment]
fixed with 622037feb4d6d21e75a29544d101dfb0c897c8e3

leaving Issue open as we are expecting new images at some stage

**Comment by pacharanero** [comment]
Closing pending this being raised as an active issue
