### ISSUE TITLE
Deprecate UKCA in favour of CE mark

### ISSUE THREAD

**Issue by pacharanero** [rcpch/digital-growth-charts-documentation#90]
It sounds like the UKCA mark is going to be phased out in favour of keeping the recognition of the Conformité Europeénne (CE) mark. At present we have a MHRA-registered medical device which is UKCA marked but we should look to add CE marking to this ASAP and document as such.

https://www.bbc.co.uk/news/uk-politics-66375185

**Comment by Raxxius** [comment]
# Summary

The current position of the UK is that it will recognise [CE Marking indefinitely except for medical devices](https://www.insideeulifesciences.com/2023/08/16/uk-government-to-recognize-ce-marks-indefinitely-other-than-for-medical-devices-and-ivds/) and IVDs. CE marking approval for medical devices will be extended till the following:

- general medical devices compliant with the EU medical devices directive (EU MDD) or EU active implantable medical devices directive (AIMDD) with a valid declaration and CE marking can be placed on the Great Britain market up until the sooner of expiry of certificate or 30 June 2028
- in vitro diagnostic medical devices (IVDs) compliant with the EU in vitro diagnostic medical devices directive (IVDD) can be placed on the Great Britain market up until the sooner of expiry of certificate or 30 June 2030, and
- general medical devices including custom-made devices, compliant with the EU medical devices regulation (EU MDR) and IVDs compliant with the EU in vitro diagnostic medical devices regulation (EU IVDR) can be placed on the Great Britain market up until 30 June 2030.
[Source](https://www.gov.uk/guidance/regulating-medical-devices-in-the-uk#full-publication-update-history) (summary of key requirements)

CE marking can only be obtained from EU approvers, with the UKCA mark being from UK Approved Bodies.

CE marking of self certified class 1 medical devices will remain valid until **_30th June 2030._**

Northern Island market does not recognise UKCA markings and will require CE marking.

## Overview

The UKs replacement of the CE Marking system with an equivalent UKCA mark has largely been rolled back for a number of fields however there remains specific rules for (relevancy highlighted)

- **_medical devices_**
- rail products
- construction products
- civil explosives
- marine equipment
- cableways
- ecodesign
- transportable pressure equipment
- hazardous substances (RoHS).

_Source: https://www.gov.uk/guidance/using-the-ukca-marking_

## Medical device regulation

_Source: https://www.gov.uk/guidance/regulating-medical-devices-in-the-uk#full-publication-update-history_ 

Last official update: 20 July 2023

The UK has extended its acceptance of CE marking:

_“As expanded on in the implementation update on work towards a strengthened future medical devices regime, the government has put in place legislation to extend acceptance of CE marked devices in Great Britain beyond 30 June 2023.”_


## Relevant transitional regulations
From my understanding Baw Medical currently has the "Growth Chart” as a self declared Class 1 medical device with a UKCA marking.

Currently CE marking be valid until 30th June 2030 (approx 6 ½ years) whereby a UKCA mark would be required.
“This will enable certain CE marked medical devices to continue to be placed on the Great Britain market for longer.
The legislation provides that you can place self-declared CE marked Class I medical devices on the GB market beyond 30 June 2023 if they are:
- self-declared against EU MDR requirements (until 30 June 2030), or
- self-declared against MDD requirements before 26 May 2021 where Notified Body involvement in their assessment is not required under MDD but is under EU MDR (until 30 June 2028). This includes upclassified devices and reusable surgical instruments.

It also provides that you can place a Class I medical device which has a sterile or measuring function with a valid MDD certificate on the GB market until 30 June 2028.”

_Source: https://www.gov.uk/government/publications/implementation-of-the-future-regulation-of-medical-devices-and-extension-of-standstill-period/implementation-of-the-future-regulations_ 

## Notifiable bodies for CE marking

UK registered notified bodies cannot provide CE marking

the EU no longer recognises UK Notified Bodies
UK Notified Bodies are not able to issue CE certificates - and have become [UK Approved Bodies](https://www.gov.uk/government/publications/approved-bodies-for-medical-devices)

_Source: https://www.gov.uk/guidance/regulating-medical-devices-in-the-uk_ 


EU registered notified bodies CE marks will be recognised as valid in the UK.

_“Certificates issued by EU-recognised Notified Bodies that are valid for the EU market, will continue to be recognised as valid for the Great Britain market.”_

_Source:
https://www.gov.uk/government/publications/implementation-of-the-future-regulation-of-medical-devices-and-extension-of-standstill-period/implementation-of-the-future-regulations_ 


## Conclusion
The UKs rollback of supporting CE markings to indefinite time does not include medical devices. At this time the UK is suggesting it will support CE marks until 30th June 2030. The UK will use the UKCA mark in place of the CE mark. CE marks are required for use in Northern Ireland. 

### Recommendation 

CE marking will be needed for future marketing outside of the UK, but the UK remains committed to the UKCA marking.

**Comment by pacharanero** [comment]
Based on @Raxxius's synopsis above, there is no need to change back to CE marking. Medical devices will continue to use UKCA.
I can therefore close this issue.
